export const Users = [
    {
        id:1,
        profilePicture: "person/1.jpeg",
        username: "Marta Botafogo",
    },
    {
        id:2,
        profilePicture: "person/2.jpeg",
        username: "Junior Junio",
    },
    {
        id:3,
        profilePicture: "person/3.jpeg",
        username: "Cleiton Rasta",
    },
    {
        id:4,
        profilePicture: "person/4.jpeg",
        username: "Jao Bragantino",
    },
    {
        id:5,
        profilePicture: "person/5.jpeg",
        username: "vermelho Flamengo",
    },
    {
        id:6,
        profilePicture: "person/6.jpeg",
        username: "verde Palmeiras",
    },
    {
        id:7,
        profilePicture: "person/7.jpeg",
        username: "Gol Quadrado",
    },
    {
        id:8,
        profilePicture: "person/8.jpeg",
        username: "cg 125",
    },
    {
        id:9,
        profilePicture: "person/9.jpeg",
        username: "Ipsum Lorem",
    },
    {
        id:10,
        profilePicture: "person/10.jpeg",
        username: "Nauro Jp",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Uma vez flamengo, sempre flamengo",
        photo: "post/1.jpeg",
        date: "5 min ago",
        userId: 1,
        like: 32,
        Comment: 9,
    },
    {
        id: 2,
        photo: "post/2.jpeg",
        date: "15 min ago",
        userId: 2,
        like: 2,
        Comment: 1,
    },
    {
        id: 3,
        desc: "Vai Palmeiras",
        photo: "post/3.jpeg",
        date: "5 min ago",
        userId: 3,
        like: 3,
        Comment: 5,
    },
    {
        id: 4,
        photo: "post/4.jpeg",
        
        date: "25 min ago",
        userId: 4,
        like: 22,
        Comment: 12,
    },
    {
        id: 5,
        desc: "Lorem ipsuim",
        photo: "post/5.jpeg",
        date: "35 min ago",
        userId: 5,
        like: 320,
        Comment: 90,
    },
    {
        id: 6,
        photo: "post/6.jpeg",
        date: "45 min ago",
        userId: 6,
        like: 24,
        Comment: 243,
    },
    {
        id: 7,
        desc: "Deixa o like",
        photo: "post/7.jpeg",
        date: "46 min ago",
        userId: 7,
        like: 54,
        Comment: 12,
    },
    {
        id: 8,
        photo: "post/8.jpeg",
        date: "55 min ago",
        userId: 8,
        like: 232,
        Comment: 49,
    },
    {
        id: 9,
        desc: "Voa mlk",
        photo: "post/9.jpeg",
        date: "55 min ago",
        userId: 9,
        like: 320,
        Comment: 90,
    },
    {
        id: 10,
        photo: "post/10.jpeg",
        date: "57 min ago",
        userId: 10,
        like: 54,
        Comment: 41,
    },
]